version: '3'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: docker_hackaton_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      DATABASE_URL: postgres://postgres_user:password@database:5432/docker_hackaton_db
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  db-volume: